# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-10 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Tcustomer',
        ),
    ]
