# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-10 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180310_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Tcustomer',
        ),
    ]
